FROM registry.redhat.io/ubi10/go-toolset:10.1 AS builder

WORKDIR /opt/app-root/src

COPY cluster-claimer/go.mod cluster-claimer/go.sum ./
RUN go mod download

COPY cluster-claimer/main.go ./
RUN CGO_ENABLED=0 go build -o /opt/app-root/cluster-claimer .

FROM registry.redhat.io/ubi10/ubi-minimal:latest

COPY --from=builder /opt/app-root/cluster-claimer /usr/local/bin/cluster-claimer

ENTRYPOINT ["cluster-claimer"]
